DELIMITER $$
CREATE FUNCTION TinhSLSP(id BIGINT, SLSPDonHang INT)
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE SLSP INT DEFAULT 0;
    DECLARE SL INT DEFAULT 0;

    SELECT Amount INTO SLSP FROM product WHERE ProductID = id;
    SET SL = SLSP - SLSPDonHang;

    RETURN SL;
END $$
DELIMITER ;